[tool.black]
line-length = 180
target-version = ["py38"]  # Remember to change this if we change pins from Python 3.9!  TODO black does not yet support 3.9 (13-01-2021)

[tool.isort]
line_length = 180
profile = "google"
py_version = "39"
skip_gitignore = true
no_lines_before = "STDLIB"
single_line_exclusions = ["dash.dependencies", "typing", "dependencies"]
known_dash = ["dash", "dash_core_components", "dash_html_components", "dash.dependencies"]
known_pandas = ["pandas", "numpy", "pyarrow"]
known_typing = "typing"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DASH"," PANDAS", "FIRSTPARTY", "LOCALFOLDER", "TYPING"]
